# Generated by Django 3.2.6 on 2021-11-20 22:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_name', models.CharField(max_length=100, verbose_name='Name')),
                ('feedback_email', models.CharField(max_length=100, verbose_name='Email')),
                ('feedback_subject', models.CharField(max_length=100, verbose_name='Subject')),
                ('feedback_message', models.TextField(max_length=500, verbose_name='Message')),
            ],
        ),
        migrations.CreateModel(
            name='LostNFound',
            fields=[
                ('reg_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('stud_num', models.CharField(blank=True, max_length=11, verbose_name='Student Number')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='Email')),
                ('contact', models.CharField(max_length=11, verbose_name='Contact Number')),
                ('lost_and_found', models.CharField(choices=[('L', 'Lost'), ('F', 'Found')], max_length=100, verbose_name='Lost & Found')),
                ('lostNfound_date', models.DateField(verbose_name='Date')),
                ('lostNfound_time', models.TimeField(blank='True', null='True', verbose_name='Time')),
                ('item', models.CharField(max_length=100, verbose_name='Item')),
                ('item_desc', models.TextField(max_length=500, verbose_name='Item Description')),
                ('pick_up_loc', models.CharField(choices=[('Recto Gate', 'RECTO GATE'), ('Gastambide Gate', 'GASTAMBIDE GATE')], default='RECTO GATE', max_length=100, verbose_name='Pick-up Location')),
                ('claimed', models.BooleanField(default=False, verbose_name='Claimed')),
                ('receiver', models.CharField(blank='True', max_length=100, null='True', verbose_name='Received by')),
                ('received_date', models.DateField(blank='True', null='True', verbose_name='Date')),
                ('received_time', models.TimeField(blank='True', null='True', verbose_name='Time')),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='User Name')),
                ('gender', models.CharField(max_length=50, verbose_name='Gender')),
                ('user_text', models.TextField(null=True, verbose_name='User Input')),
                ('user_session', models.CharField(max_length=150, null=True, verbose_name='User Session')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('visits', models.IntegerField(null=True, verbose_name='Number of visit')),
            ],
            options={
                'db_table': 'user_session',
            },
        ),
    ]
